# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongnumber',
            name='Phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
